### PR TITLE
Add Introduction to ML and NNs with DeepPumas

### PR DESCRIPTION
**Pull request by andreuvall**
Add workshop "Introduction to Machine Learning and Neural Networks". 

Note: the "Glossary" section under the "Reference Sheet" page is missing for now. I plan to write it some time soon, but not right now, and it doesn't seem so critical as to leave the workshop unpublished.

### CODE REVIEW

**Review by jotas6 — COMMENTED** [review]
I am not sure if this is intentional, but it seems like the workshop repository is not public yet, so I can't access the links:

image

I am also not able to find it as a repository on PumasAI-Labs

**Comment by storopoli** [comment]
We should make the repo public before adding here.

**Comment by andreuvall** [comment]
I tried switching the repository visibility to "public" as described [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility), but I don't seem to have the rights for that. I have this message 

> **Change repository visibility**
> Organization members can’t change repo visibility. 

Do you know who has the rights for that?

In the meanwhile, I gave you both access, @storopoli and @jotas6, as "admin".

**Comment by storopoli** [comment]
Done!
CI for the new GH Pages is already running

**Review by jotas6 — APPROVED** [review]
Everything is working well now. I was able to access all the links

**Comment by andreuvall** [comment]
For me, the workshop website doesn't display correctly. I get redirected to the anonymous link, and also get a 404 error.

**Comment by jotas6** [comment]
The same as happening to me, but it got fixed after deleting the browser cache. You can also try it in an incognito/private window

**Comment by andreuvall** [comment]
You are right! Thank you!

**Pull request merged**
